#!/bin/bash
echo "[$(date)] Hook started" >> /var/log/webhook.log
git --work-tree=/var/www/html --git-dir=/var/www/html.git checkout -f main 2>&1 >> /var/log/webhook.log
echo "[$(date)] Hook finished" >> /var/log/webhook.log
